server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 'Rohan*5631'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect