FROM openjdk:17-jdk-slim

#maintainer name
MAINTAINER Learn

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

#execute the application
CMD ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]