server:
  port: 8072
spring:
  application:
    name: "gatewayserver"
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "API Gateway application"
    version: "1.0"

logging:
  level:
    com:
      learningproj:
        gateway: DEBUG
