server:
  port: 8072
spring:
  application:
    name: "gatewayserver"
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 15s
      discovery:
        locator:
          enabled: false
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveliness-state:
      enabled: true
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: "gatewayserver"
    description: "API Gateway application"
    version: "1.0"

logging:
  level:
    com:
      learningproj:
        gateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold : 50
      waitDurationInOpenState: 10000

