server:
  port: 8072
spring:
  application:
    name: "gatewayserver"
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveliness-state:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "API Gateway application"
    version: "1.0"

logging:
  level:
    com:
      learningproj:
        gateway: DEBUG
