spring:
  config:
    activate:
      on-profile: "qa"
accounts:
  message: "Welcome to accounts related local APIs QA profile"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@abcbank.com"
  onCallSupport:
    -(055)555-123
    -(055)555-456
