server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 'Rohan*5631'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    sql:
      init:
        mode: always
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      busrefresh:
        enabled: true
