services:
  network-deploy-service:
    networks:
      - loansNetwork
      
  microservice-base-config:
    extends:
      service: network-deploy-service 
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  microservice-eureka-server-config:
    depends_on: 
      config-server:
        condition: service_healthy 
    extends:
      service: network-deploy-service
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"

  microservice-gateway-server-config:
      depends_on: 
        config-server:
          condition: service_healthy 
        eureka-server:
          condition: service_healthy 
        loans:
          condition: service_healthy 
        cards:
          condition: service_healthy 
        accounts:
          condition: service_healthy
      extends:
        service: network-deploy-service
      environment:
        SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
        SPRING_PROFILES_ACTIVE: "default" 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE  : "http://eureka-server:8070/eureka"
    
  microservice-configs:
    extends: 
      service: microservice-base-config
    depends_on: 
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
      SPRING_PROFILES_ACTIVE: "prod"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE  : "http://eureka-server:8070/eureka"