services:
  # rabbit:
  #   image: "rabbitmq:management-alpine"
  #   container_name: rabbit
  #   ports:
  #   - "5672:5672"
  #   - "15672:15672"
  #   healthcheck:
  #     test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s
  #   extends:
  #     file: docker-compose-common.yaml
  #     service: network-deploy-service

  config-server:
    image: "martialtech/config-server:v4"
    container_name: config-server-ms
    ports:
      - "8071:8071"
    # depends_on:
    #   rabbit:
    #    condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: docker-compose-common.yaml
      service: microservice-base-config
    environment:
      SPRING_APPLICATION_NAME: "config-server"

  eureka-server:
    image: "martialtech/eureka-server:v1"
    container_name: eureka-server
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: docker-compose-common.yaml
      service: microservice-eureka-server-config
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"

  gateway:
    image: "martialtech/gateway:v1"
    container_name: gateway
    ports:
    - "8072:8072"
    extends:
      file: docker-compose-common.yaml
      service: microservice-gateway-server-config
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"      

  accounts:
    image: "martialtech/accounts:v4"
    container_name: accounts-ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
    - "8080:8080"
    extends:
      file: docker-compose-common.yaml
      service: microservice-configs
    environment:
      SPRING_APPLICATION_NAME: "accounts"

  cards:
    image: "martialtech/cards:v4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: docker-compose-common.yaml
      service: microservice-configs
    environment:
      SPRING_APPLICATION_NAME: "cards"

  loans:
    image: "martialtech/loans:v4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: docker-compose-common.yaml
      service: microservice-configs
    environment:
      SPRING_APPLICATION_NAME: "loans"
   
networks:
  loansNetwork:
    driver: "bridge"
