services:
  network-deploy-service:
    networks:
      - loansNetwork
      
  microservice-base-config:
    extends:
      service: network-deploy-service 
    deploy:
      resources:
        limits:
          memory: 700m
    
  microservice-config-server-config:
    extends: 
      service: microservice-base-config
    depends_on: 
      config-server:
        condition: service_healthy 
      mysql:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_RABBITMQ_HOST: "rabbit"