services:
  network-deploy-service:
    networks:
      - loansNetwork
      
  microservice-base-config:
    extends:
      service: network-deploy-service 
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-eureka-server-config:
    depends_on: 
      config-server:
        condition: service_healthy 
    extends:
      service: network-deploy-service
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"

  microservice-gateway-server-config:
      depends_on: 
        config-server:
          condition: service_healthy 
        eureka-server:
          condition: service_healthy 
        loans:
          condition: service_healthy 
        cards:
          condition: service_healthy 
        accounts:
          condition: service_healthy
      extends:
        service: network-deploy-service
      environment:
        SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
        SPRING_PROFILES_ACTIVE: "default" 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE  : "http://eureka-server:8070/eureka"
    
  microservice-configs:
    extends: 
      service: microservice-base-config
    depends_on: 
      eureka-server:
        condition: service_healthy 
      gateway:
        condition: service_healthy 
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
      SPRING_PROFILES_ACTIVE: "default"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE  : "http://eureka-server:8070/eureka"